name: Build and Commit Dist

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20" # Specify the Node.js version you want to use

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npm run build

      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Configure Git
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

          # Create an orphan branch main-dist
          git checkout --orphan main-dist

          # Remove all files from the working tree
          git rm -rf .

          # Add the dist folder
          git add dist
          git add package.json

          # Commit the dist folder
          git commit -m 'Build: Update dist folder'

          # Force push to the main-dist branch
          git push origin main-dist --force
        if: success()
